name: ai_companion_frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.7
    cupertino_icons: ^1.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    assets:
        - lib/assets/logo.png
    uses-material-design: true
